apiVersion: v1
kind: Service
metadata:
  name: service1-service
  labels:
    app: service1-sample
spec:
  type: NodePort
  selector:
    app: service1-view
  ports:
   - protocol: TCP
     port: 8081
     nodePort: 30111
     targetPort: 3000

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service1-deployment
spec:
  replicas: 2
  template:
    metadata:
      name: service1
      labels:
        app: service1-view
    spec:
      containers:
        - name: service1
          image: "registry.eu-gb.bluemix.net/kubernetestutorial/service1:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: containerregistrysecret
